### ISSUE TITLE
Causing issues with SponsorBlock

### ISSUE THREAD

**Issue by JonnyXX88** [z0ccc/Upvote-Anywhere#22] opened 2021-10-22 04:18 UTC
Firefox 93.0

Reddit Wherever is causing SponsorBlock's timeline segments to be misaligned.

Without Reddit Wherever:
![image](https://user-images.githubusercontent.com/53140473/138392795-3c782c53-814f-41ae-8eab-45aea0bc9a1f.png)

With Reddit Wherever:
![image](https://user-images.githubusercontent.com/53140473/138392822-6bf2e771-11c2-4ad9-93f2-530744b3e54f.png)

**Comment by z0ccc** [comment] 2021-10-22 04:50
I can't seem to replicate this issue. Can you post a URL for a video where its happening?

**Comment by mnxn** [comment] 2022-01-06 08:46
The cause is here:
https://github.com/z0ccc/Upvote-Anywhere/blob/0c1c7476e7870194e2cab632501bf92d10ae4ff0/src/styles/App.css#L313-L317

The CSS rule is being applied to all `ul`s on the page, including the SponsorBlock segment preview.

Prefixing the selectors with `#redComments` will make them only active in the reddit comments section and should fix this issue.

**Comment by z0ccc** [comment] 2022-01-07 02:50
@mnxn Thanks a lot! Been busy with work/ other projects so I haven't been able to work on this. This will be in the next release.

**Closed by z0ccc** 2022-01-07 02:50 UTC

**Comment by mnxn** [comment] 2022-01-07 03:23
The extension just updated on Firefox and it works perfectly now for me, thank you!

**Comment by z0ccc** [comment] 2022-01-07 03:58
No Thank you lol
